from .ants import Ant
from .betta_fish import BettaFish
from .copperhead_snake import CopperHead
from .earthworms import EarthWorms
from .finches import Finch
from .gerbils import Gerbil
from .mice import Mice
from .parakeets import Parakeet
from .terrapins import Terrapins
from .timber_rattlesnake import Rattlesnake
